In [2]:
# NumPy Mastery Practice — Data Analytics Track

In [ ]:
# # In programming, the difference between a function and a method comes down to "who owns it" and how you call it.

# # 1. The Distinction
# # np.delete() is a Function: It belongs to the NumPy library itself. You call it by passing the array into it as an argument.

# # Methods are functions that "live" inside an object. You call them using a dot after the object name (e.g., arr.reshape()).

# Type,Syntax,Example
# Function,library.name(object),"np.delete(arr, 0)"
# Method,object.name(),arr.mean()

In [3]:
# SECTION 1: Array Creation & Understanding (Foundation)
# Goal:
# Understand how NumPy arrays work and why they replace Python lists.

In [4]:
# Exercise 1.1

# Task

    # Import NumPy

    # Create a 1D array [10, 20, 30, 40, 50]

    # Print it

In [5]:
import numpy as np
arr=np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [6]:
# Exercise 1.2

# Task

    # Create five zeros

    # Create five ones

    # Create numbers from 1 to 20 with step 3

    # Create five evenly spaced numbers between 0 and 1

In [7]:
arr1=np.zeros(5)
arr2=np.ones(5)
arr3=np.arange(1,21,3) #generates evenly spaced values inside an array
arr4=np.linspace(0,1,5)

print(arr1,'\n',arr2,'\n',arr3,'\n',arr4)


[0. 0. 0. 0. 0.] 
 [1. 1. 1. 1. 1.] 
 [ 1  4  7 10 13 16 19] 
 [0.   0.25 0.5  0.75 1.  ]


In [8]:
# LEVEL 2: VECTORS, ARRAYS & TENSORS
# Task

    # Identify vector / matrix / tensor

    # Print dimensions



In [9]:
a = np.array([1, 2, 3])
b = np.array([[1, 2], [3, 4]])
c = np.array([[[1]]])
# sol
# The ndim attribute in NumPy is used to determine the number of dimensions (axes) of an array
print(a.ndim) #vector
print(b.ndim) #matrix
print(c.ndim)  #3d array/tensor       (list inside a list inside a list inside a list)



1
2
3


In [10]:
# Exercise 2.2

    # Convert [5, 10, 15, 20] into:

        # Row matrix

        # Column matrix

In [33]:
a=np.array([5, 10, 15, 20])
print(a.reshape(1,-1))
print(a.reshape(-1,1))
# use -1 as a wildcard for one dimension to let NumPy infer its size automatically. 
# Example: reshaped_array = array.reshape((-1, 3)) will calculate the number of rows automatically.
# The 1: This specifies the first dimension. You are telling NumPy: "I want exactly one row."
# The -1: This is a "wildcard" or placeholder. It tells NumPy: "I don't want to do the math—you figure out how many columns are needed to 
# "fit all the elements." # Since you have 4 numbers, NumPy calculates that -1 must be 4.

[[ 5 10 15 20]]
[[ 5]
 [10]
 [15]
 [20]]


In [ ]:
# Create [100, 200, 300]

    # Save it

    # Load it   

In [ ]:
arr=np.array([100,200,300])
np.save("data.npy",arr)         #creates a npy file containing the array(data)
np.load("data.npy")             #loads the file

array([100, 200, 300])

In [ ]:
# LEVEL 4: ARRAY FEATURES
# data = np.array([[10, 20, 30],
#                  [40, 50, 60]])

# Task
    # Find shape, size, dtype, dimensions, memory size.



In [50]:
data = np.array([[10, 20, 30],[40, 50, 60]])
print(data)
print(data.shape)        #Change layout	Adds/Removes/Rearranges brackets
print(data.size)         #Total number of elements
print(data.dtype)        #tells how much memory the array takes up
print(data.ndim)         #Finding the dimensions of a NumPy array
print(data.itemsize)
print(data.itemsize+data.size)  #Total Memory = Number of Elements * times Item Size(total bits used by the array) use nbytes alternatively

[[10 20 30]
 [40 50 60]]
(2, 3)
6
int64
2
8
14


In [ ]:
# # LEVEL 5: INDEXING & SLICING
# Task

    # First element

    # Last element

    # Elements from 20 to 40
# arr = np.array([10, 20, 30, 40, 50])

In [54]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[0])
print(arr[-1])
print(arr[1:4])

10
50
[20 30 40]


In [ ]:
# Exercise 5.2
# mat = np.array([[100, 200, 300],
#                 [400, 500, 600]])

# Task

    # Extract 500

    # First row

    # Second column

In [61]:
mat = np.array([[100, 200, 300],
                [400, 500, 600]])
print(mat[1,1])
print(mat[1:])
print(mat[:,1])

500
[[400 500 600]]
[200 500]


In [ ]:
# LEVEL 6: ARITHMETIC OPERATIONS & VECTORIZATION
# Exercise 6.1

    # Increase all values by 10%
    # prices = np.array([100, 200, 300])


In [62]:
prices = np.array([100, 200, 300])
print(prices*1.10)

[110. 220. 330.]


In [ ]:
# # a = np.array([10, 20, 30])
# # b = np.array([1, 2, 3])

# Task
    # Add and multiply.

In [63]:
a = np.array([10, 20, 30])
b = np.array([1, 2, 3])
print(a+b)
print(a*b)

[11 22 33]
[10 40 90]


In [ ]:
# LEVEL 7: BROADCASTING
# Exercise 7.1

    # Add 18% tax to prices.
    # prices = np.array([100, 200, 300])


In [65]:
prices = np.array([100, 200, 300])
print(prices+prices*0.18)


[118. 236. 354.]


In [ ]:
# # Exercise 7.2
# sales = np.array([[100, 200, 300],
#                  [400, 500, 600]])

# bonus = np.array([10, 20, 30])
# Add bonus to each row.


In [67]:
sales = np.array([[100, 200, 300],
                  [400, 500, 600]])
bonus = np.array([10, 20, 30])
print(sales+bonus)



[[110 220 330]
 [410 520 630]]


In [ ]:
# LEVEL 8: AGGREGATION & STATISTICS

# Exercise 8.1
    # sales = np.array([12000, 15000, 18000, 20000])
# Task
    # Total, average, max, min.

In [74]:
sales = np.array([12000, 15000, 18000, 20000])
print(np.sum(sales))
print(np.round(np.mean(sales),2))
print(np.max(sales))
print(np.min(sales))


65000
16250.0
20000
12000


In [ ]:
# # # Exercise 8.2
# # data = np.array([[10, 20, 30],
# #                  [40, 50, 60]])
# Task
    # Row-wise sum, column-wise mean.

In [ ]:
data = np.array([[10, 20, 30],[40, 50, 60]])
print(data,'\n')
print(np.sum(data,axis=1),'\n')      #axis=1 --> row-wise
print(np.mean(data,axis=0),'\n')    #axis=0 ---> column-wise


[[10 20 30]
 [40 50 60]] 

[ 60 150] 

[25. 35. 45.] 



In [ ]:
# LEVEL 9: BOOLEAN MASKING & CONDITIONALS
# Exercise 9.1
    # scores = np.array([45, 67, 89, 34, 72])

# Task
    # Scores > 60
    # Scores between 50 and 80


In [ ]:
scores = np.array([45, 67, 89, 34, 72])
print(scores[scores>60])                        # Boolean indexing
print(scores[(scores>=50)&(scores<=80)])

[67 89 72]
[67 72]


In [ ]:
# Exercise 9.2
# Replace values below 50 with 50.

scores = np.array([45, 67, 89, 34, 72])
scores[scores<50]=50
print(scores)

[50 67 89 50 72]


In [ ]:
# LEVEL 10: DELETION, SORTING & SEARCHING

# Exercise 10.1

# arr = np.array([10, 20, 30, 40, 50])
# Delete index 2.

In [ ]:
arr = np.array([10, 20, 30, 40, 50])
arr=np.delete(arr,2)    #removes the elememt present at index 2 of arr
arr

array([10, 20, 40, 50])

In [ ]:
# Exercise 10.2
# arr = np.array([3, 1, 2, 3, 2])
# Sort and get unique values

In [105]:
arr = np.array([3, 1, 2, 3, 2])
print(np.sort(arr))
print(np.unique(arr))

[1 2 2 3 3]
[1 2 3]


In [ ]:
# # LEVEL 11: MISSING VALUES
# data = np.array([10, 20, np.nan, 40])
# Detect missing and compute mean ignoring NaN.

In [112]:
data = np.array([10, 20, np.nan, 40])
print(np.isnan(data))
print(np.round(np.nanmean(data),2))

[False False  True False]
23.33


In [ ]:
# LEVEL 12: RANDOM DATA

# Exercise 12.1
# Generate 10 random integers between 50 and 100.

In [ ]:
# Generate 10 random integers between 50 and 100.
arr=np.random.randint(50,101,10)
print(arr)

# Breakdown of the numbers:
# 50 (Low): The smallest possible number you can get. This is inclusive.
# 101 (High): The upper bound. This is exclusive, meaning it will never actually pick 101. The highest possible number it will return is 100.
# 10 (Size): This tells NumPy to create a 1D array with 10 elements.

[79 88 76 60 78 73 57 70 79 81]


In [123]:
# Create a 3x4 matrix (3 rows, 4 columns)
arr_2d = np.random.randint(50, 101, size=(3, 4))
arr_2d

array([[ 51,  52,  68,  69],
       [ 62,  77,  94,  64],
       [ 83,  60, 100,  50]], dtype=int32)

In [122]:
# Create 3d matrix
arr_3d = np.random.randint(50, 101, size=(2, 3, 2))
arr_3d

array([[[75, 88],
        [74, 86],
        [69, 50]],

       [[80, 95],
        [52, 79],
        [89, 95]]], dtype=int32)

In [ ]:
# LEVEL 13: FINAL INTEGRATED PRACTICE
# revenue = np.array([12000, 15000, 18000, 9000, 22000, 17000])

# Tasks

# Total revenue
# Average revenue
# Values above average
# Sorted descending
# Percentage growth from min to max

In [148]:
revenue = np.array([12000, 15000, 18000, 9000, 22000, 17000])
tot_rev=np.sum(revenue)
print(f"Total revenue {tot_rev}")

avg_rev=np.mean(revenue)
print(f"Average revenue{avg_rev}")

print(f"Value greater than average revenue{revenue[revenue>avg_rev]}")

sorted=np.sort(revenue)[::-1]
print(f"Descending sort {sorted}")

minimum=np.min(revenue)
maximum=np.max(revenue)
growth=np.round((maximum-minimum)/minimum,2)
print(growth)

Total revenue 93000
Average revenue15500.0
Value greater than average revenue[18000 22000 17000]
Descending sort [22000 18000 17000 15000 12000  9000]
1.44


In [152]:
# # Q. Flatten this matrix:
# mat = np.array([[1, 2],
#                 [3, 4]])

mat = np.array([[1, 2],
                [3, 4]])
print(mat.flatten())


[1 2 3 4]
